# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pasta from Fat Joey
email: shuyangs@usc.edu
description: > # this means to ignore newlines until "baseurl:"
  This is where I would ramble on about the small technical things I found useful. 
  I started this after struggling with feeding data into LMDB format and then into
  Caffe. Why so many inconclusive tutorials while two simple example code snippets 
  would suffice?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shengshuyang.github.io" # the base hostname & protocol for your site
twitter_username: faatJoey
github_username:  shengshuyang

# Build settings
markdown: kramdown
