# User Settings | Edit there as per required

title: Shuyang Sheng's Blog
url: "http://shengshuyang.github.io/"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    Shuyang Sheng<span class="faded">'s Blog</span>

email: shuyangs@usc.edu
author: Shuyang Sheng
# This description will show up in google search results
# (for index page) etc.
description: >
    Shuyang Sheng's technical blog.

# This will what will show against &copy; in the footer
copyright: accent
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
  This is where I would ramble on about the small technical things I found useful. 
  I started this after struggling with feeding data into LMDB format and then into
  Caffe.

permalink: /:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    PhD student at USC working on computer vision.

about_footer: true

twitter_username: faatJoey
github_username: shengshuyang
favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 20
paginate_path: "/page/:num"
tracking_id: UA-69243698-7 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/accent.png" # This will show in facebook thumbnails
twitter_image: "http://ankitsultana.me/images/accent.png?1234" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
